url:
  - https://link.onesy.link/link/xQ3S0L9bt
  - https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=db7210cdd132746b50227ca6

rule_set:
  - label: 规则集标签A
    value:
      type: local
      path: /usr/
      china: true
  - label: 规则集标签B
    value:
      type: remote
      path: sas
      china: false
