url:
  - https://link.onesy.link/link/xQ3S0L
  - https://sub1.smallstrawberry.com/api/v1/client/a66fb16ac4
rule_set:
  # - 规则集标签A:
  #     type: local
  #     path: /usr/
  #     china: true
  # - 规则集标签B:
  #     type: remote
  #     url: sas
  #     china: false
